"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(5bmxnyu3_%*$_n2qi1339%5^zwu41ba+_g*pba^@)&*v7u7b0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 'django.contrib.staticfiles',
    'demo_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'https://django-itaims.s3.ap-south-1.amazonaws.com/'
# STATIC_URL = 'https://d255uh0a5ty4v7.cloudfront.net/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'

AWS_ACCESS_KEY_ID=os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY=os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME=os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME=os.getenv('AWS_S3_REGION_NAME')
AWS_QUERYSTRING_EXPIRE=5
AWS_S3_CUSTOM_DOMAIN = 'd255uh0a5ty4v7.cloudfront.net'
AWS_CLOUDFRONT_KEY_ID = os.getenv('AWS_CLOUDFRONT_KEY_ID')
AWS_IS_GZIPPED=True
AWS_CLOUDFRONT_KEY = """
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAzEhsnWEGKJgV0bcfkT1fMRKk8Uu1w4uN2TWYWOH8kinFuGNh
P451CjrL+JCCmVE6MJLlny6hP/rFX7Ij7fIhWoZW0oB8bxkjAh56M9zVzZTL/YsO
xI8w0jxbKI7fTdeR/5i1FUbQrB0o6dBAh2XZk9B/T3pbjF59PpVb/9S9vgp6tueE
J0hKkbssHW8FHM5losT01sUVn3Nz+zI29QjNQt1ZTJl3Od+2oCQPwTH6VHfo456n
nB2Ep8uZAMq/yr7mVgPwt8DStEir0Wb+oDdJ2Fc/8SUHOtc0wutVNb1F/wCj83VZ
3qbYXwz6YoCrwhy0ccVCNOhg5VdDto+GMehDbQIDAQABAoIBAAQOKAHTzECADGbW
YM0MT9h0i0uy+g/AtHcsZjLVgaMRKzim2GZfmJk0Y5oynDUY9LPEJsTLMy5G9yYY
LjhqBxl58z1Iia/W6uf+3OQsrR3gp1AIM6nZQdnakuCyPWKZNe/CA05B0qCoD4jc
tns5nWEe0XgtcKXPtmLIqkPg4Edmer/gm957PZpV6Ltn03C2YVBZFKvhOr+HRshs
JCEy+x6Ygb7rshplO4ilcNCm2zukHl4b1iEUmoFbejMd+g5uHCxaA8fbZ00eviNX
P7HZimfjMy1jdXTTcm6CP1r9STSyBMRj8r90MV4WwCWm05Hym/jYkVSQgGo/mkJJ
gwCwKcECgYEA9wcGqiLtsJfWNp0b8/KpL46dHeaH1m6l1zfrgfyC2eBGohyFG96o
XV81sFNeASbkrCH6bdQpsdnO2w1KBXVpZoyxpRGk+9QzDENC6XptVx6Zj7a5ox/D
+wJHgkJTH4250W5zMKd5Iurxp2T9IS0qkNATMEVdW41k1SUJ755oA90CgYEA07Pw
pKySd9I+FVD9Tg7UVTjf0T1krKSyZYd4+MpCl5N2Lljr0TRi2WA5DiTj7z3WiBNC
+UGcJRAbIctTogzjpXnJ6BuLkxU0RNO41cSJjbKJulg0IPNYoqP5ckoQlKNoxdh+
4xXvkGev1yRId1e27TupYJ5PNNCQiVnhbG19zNECgYAEW3deoOcYalU4+WR41Rru
39EdqedTfPgn57Cbxlx4g2A7k801RKQroXZM+et6kbkO4DqOnWNu46ymaIGZvwxw
5qJrivgiCQgtezI+9A3hr4R96Hc1zWWjk9K3FXxp3hIdA5m8jfexCfvhPALLBwTt
MP5lp5OR/dh9ef3G4EBtcQKBgA7UiSQQDsakDMNThBsmwMsji9JNmbLaasDgB6Ju
ENIre1jt0785Cz+tFPIftXP6AgBQUR3C8dxKz4vDgZ1Vh9D8wh8nZtSr5Jh5uHYJ
KZWqjyllqmkwguIJ2JygAZ9X/yv06Zag38Je8RuCKC1sEJ1303q4PFY30hg9GqSM
2wYxAoGBAJ9WEcD2MqAKBQIwp7r1CebvrqAwtjcraJAzyNeoz2OtgRYbdH2HRGpp
pPJvkt1XmTQOf8fgQPAia4dpTjEN/vkZOQu26wNLQhNeu0UPLAdtXoscZNqZXVfe
REXO+ye5XeWQSyj1Sdam7VzuYf+t76UYrirQqD7Nr1eSLmAQkYou
-----END RSA PRIVATE KEY-----
"""