# Generated by Django 4.2.3 on 2023-07-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.ImageField(upload_to='blogs/'),
        ),
    ]
